FS-001: add project config. Add store with config. Add i18n support.
MykhailoForge/prep-proj pull request #1
Opened 2023-06-01 14:57 UTC by MykhailoForge

2023-06-01 15:55 UTC, NickForge commented on src/App.tsx
> +          {t("buttonText.stack")}
it is not necessary add "Text" postfix because in translation only text

2023-06-01 16:11 UTC, NickForge requested changes

2023-06-01 16:11 UTC, NickForge commented on src/components/QueueVisualizer/index.tsx
> +    string | number
why there can be string or number?

2023-06-01 16:11 UTC, NickForge commented on src/components/QueueVisualizer/index.tsx
> +export default function QueueVisualizer() {
better use export const QueueVisualizer = () => .... 
And file name should be same as component. It's easier to navigate between files.

2023-06-01 16:11 UTC, NickForge commented on src/components/QueueVisualizer/index.tsx
> +    (state) => state.dataVisualizer.queueVisualizerQueue
You can add selector in store and reuse in other components

2023-06-01 16:11 UTC, NickForge commented on src/components/UI/DataListLayout.tsx
> +        {[...dataList].reverse().map((item, index) => (
Why we copy and reverse this arr?

2023-06-01 16:11 UTC, NickForge commented on src/components/UI/DataListLayout.tsx
> +          <ListItem key={index}>{item}</ListItem>
for key better use something unique

2023-06-01 16:11 UTC, NickForge commented on src/components/UI/UIItems.tsx
> +import { Box, Button, Paper } from "@mui/material";
is it component?

2023-06-01 16:11 UTC, NickForge commented on src/components/StackVisualizer/index.tsx
> +    if (stackVisualizerInput !== EMPTY_STRING) {
just `if (stackVisualizerInput) {`

2023-06-01 16:11 UTC, NickForge commented on src/components/StackVisualizer/index.tsx
> +    if (stackVisualizerInput !== EMPTY_STRING) {
only if there can't be 0 as number

2023-06-01 16:11 UTC, NickForge commented on src/redux/slices/dataVisualizer/index.ts
> +        .reverse();
why you use reverse two times?

2023-06-01 16:13 UTC, NickForge commented on src/App.tsx
> +          {t("buttonText.stack")}
it can be some alike "common.stack"

2023-06-01 16:14 UTC, NickForge commented
Please check and fix similar comments in other components =)

2023-06-02 09:09 UTC, NickForge commented on src/components/UI/DataListLayout.tsx
> +  inputValue: string | number;
make it as string

2023-06-02 09:11 UTC, NickForge commented on src/components/UI/DataListLayout.tsx
> +          <ListItem key={v4()}>{item}</ListItem>
it should be part of object, because key will be created each rerender.

2023-06-02 09:13 UTC, NickForge commented on src/components/UI/UIItems.tsx
> +import { Box, Button, Paper } from "@mui/material";
it more looks like util

2023-06-02 09:15 UTC, NickForge commented on src/i18n.ts
> +      en: {
please add separate file for resources

2023-06-02 09:20 UTC, NickForge requested changes

2023-06-02 09:20 UTC, NickForge commented on src/redux/slices/dataVisualizer/index.ts
> +  stackVisualizerList: [1, 2, 3],
probably it should be as string too

2023-06-02 09:20 UTC, NickForge commented on src/redux/slices/dataVisualizer/index.ts
> +      action: PayloadAction<number | string>
same

2023-06-02 09:20 UTC, NickForge commented on src/redux/slices/dataVisualizer/index.ts
> +    queueVisualzierEnqueue: (state, action: PayloadAction<number | string>) => {
same

2023-06-02 09:20 UTC, NickForge commented on src/redux/slices/dataVisualizer/types.ts
> +  queueVisualizerQueue: (number | string)[];
same

2023-06-02 09:22 UTC, NickForge commented
Please add 👍  to each fixed comment

2023-06-02 12:20 UTC, NickForge requested changes

2023-06-02 12:20 UTC, NickForge commented on src/redux/slices/dataVisualizer/types.ts
> +}
there are the same. Maybe use one interface for value like:
```
interface Element {
  id: string;
  value: string;
}
```

2023-06-02 12:20 UTC, NickForge commented on src/translation/recources.json
> +        }
Should be separated file for en.
You have to able support different languages. And in this realization resources file will be huge and unreadable.

Please create en.json file for translations

2023-06-02 12:41 UTC, NickForge commented on src/components/UI/UIItems.tsx
> +import { Box, Button, Paper } from "@mui/material";
I've understood, my failed. It's customization of material components. Thanks =)

2023-06-02 13:40 UTC, stanislavSoro commented on src/translation/recources.json
> +        }
@NickForge it will be implemented as a part of this issue https://github.com/MykhailoForge/prep-proj/issues/2

2023-06-02 13:42 UTC, stanislavSoro commented on src/App.tsx
> +          {t("buttonText.stack")}
It will be done as a part of https://github.com/MykhailoForge/prep-proj/issues/2

2023-06-02 15:22 UTC, stanislavSoro approved these changes

2023-06-02 15:22 UTC, stanislavSoro commented
Lgtm!

2023-06-02 20:42 UTC, merged